# My practice with Panel Dashboard

## Step 0. Load libra

In [1]:
import pandas as pd
import panel as pn
import seaborn as sns
import hvplot.pandas
from panel.interact import interact

pn.extension()

## Step 1. Load data

In [2]:
df = sns.load_dataset('titanic')
df.head(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

## Step 2. Data Pre-processing

In [3]:
df['FamilySize'] = df['sibsp'] + df['parch'] + 1
df.head(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,FamilySize
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1

In [5]:
df.drop(columns=['class', 'who', 'deck', 'embarked'], axis = 1, inplace = True)

# check null values
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
adult_male       0
embark_town      2
alive            0
alone            0
FamilySize       0
dtype: int64

In [7]:
# replace
df['age'].fillna(df['age'].mean())

# drop
df.dropna(subset = ['embark_town'], inplace = True)

# check null values
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
adult_male     0
embark_town    0
alive          0
alone          0
FamilySize     0
dtype: int64

## Step 3. Create and Add Widgets and Plots

## Step 4. Layout Design